### ISSUE TITLE
Tasks, Features, and Stability improvements to reach 1000 beta users

### ISSUE THREAD

**Issue by hashmesan** [hashmesan/harmony-totp#17]
## Tasks
- [ ] Feedback changes/response [#8](https://github.com/hashmesan/harmony-totp/pull/8)
- [ ] Copywriting improvements
- [x] Documentations
- [x] design new flows, set daily limits, approval higher limit tx, transactions

## Features:
- [x] #20 Command line interface
- [x] #16 Daily Limit approval with 2FA
- [x] #14 Rebuild the hash generation and serialization as byte[] for better efficiency than hex string
- [x] #19
- [x] #23
- [x] Set daily limit 
- [ ] #18
- [x] #21

## Stability
- [x] Build tests for common codes 
- [x] Setup automated tests on github
- [x] Incorporate IPFS upload as part of wallet setup
- [x] Better error handling on recovery, etc
- [x] Move ENS lookup and other functions toward client side (less reliant on relayer)
- [x] #22
- [x] #26
- [ ] Deposit wallet mismatch when deploying new code
