### ISSUE TITLE
M4 VIPERSWAP, security audit merge & mobile UI

### ISSUE THREAD

**Issue by hashmesan** [hashmesan/harmony-totp#39]
**Tasks**

- [x] fully implemented VIPER functionality
- [x] Dapps page
- [x] merge security-fixes to security-audit -> develop
- [x] audit-fix: startRecoverCommit needs secretHash; need to update libraries, UI and retest
- [x] #42
- [x] #41
- [x] NPM publish CLI with latest fixes
- [x] #52
- [x] Write tests to validate security features
- [ ] Mobile UI update for all screens (big)
- [ ] Add token page has pre-created list
- [x] link stats page on viper liquidity , etc
- [x] #48
- [ ] #53
- [x] #46
- [x] #47

**Comment by hashmesan** [comment]
Deferring all web UI toward Atomic refactor. This milestone is complete.
